name:                srtree
version:             2.0.0.2
synopsis:            A general library to work with Symbolic Regression expression trees.
github:              "folivetti/srtree"
license:             BSD3
author:              "Fabricio Olivetti de França"
maintainer:          "fabricio.olivetti@gmail.com"
category:            Math, Data, Data Structures
copyright:           "2023 Fabricio Olivetti de França"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A Symbolic Regression Tree data structure to work with mathematical expressions with support to first order derivative and simplification;

dependencies:
- base >= 4.16 && < 5
- mtl >= 2.2 && < 2.4
- containers >= 0.6.7 && < 0.8
- unordered-containers >= 0.2 && < 0.3
- random >= 1.2 && < 1.3
- vector >= 0.12 && < 0.14
- dlist >= 1.0 && < 1.1
- massiv >= 1.0.4.0 && < 1.1
- filepath >= 1.4.0.0 && < 1.6
- split >= 0.2.5 && < 0.3
- zlib >= 0.6.3 && < 0.8
- bytestring >= 0.11 && < 0.13
- statistics >= 0.16.2.1 && < 0.17  
- attoparsec >= 0.14.4 && < 0.15
- attoparsec-expr >= 0.1.1.2 && < 0.2 
- transformers >= 0.6.1.0 && < 0.7
- ieee754 >= 0.8.0 && < 0.9
- lens >= 5.2.3 && < 5.4
- exceptions >= 0.10.7 && < 0.11 
- hashable >= 1.4.4.0 && < 1.6
- list-shuffle >= 1.0.0.1 && < 1.1
- scheduler >= 2.0.0.1 && < 3
- unliftio >= 0.2.10 && < 1
- unliftio-core 

library:
  source-dirs: src
  #extra-include-dirs: /usr/local/include
  extra-lib-dirs: /usr/local/lib
  extra-libraries:     nlopt
  ghc-options:
    - -fwarn-incomplete-patterns
    - -fdistinct-constructor-tables
    - -finfo-table-map
    - -threaded

executables:
  tinygp:
    main:                Main.hs
    source-dirs:         apps/tinygp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O3
    dependencies:
    - optparse-applicative >= 0.17 && < 0.19
    - srtree
  srtools:
    main:                Main.hs
    source-dirs:         apps/srtools
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O3
    dependencies:
    - srtree
    - optparse-applicative >= 0.17 && < 0.19
    - normaldistribution >= 1.1.0.3 && < 1.2 
  eqsatrepr:
    main:                Main.hs
    source-dirs:         apps/eqsatrepr
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O3
    dependencies:
    - srtree
  srsimplify:
    main:                Main.hs
    source-dirs:         apps/srsimplify
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O3
    dependencies:
    - optparse-applicative >= 0.17 && < 0.19
    - srtree
  egraphGP:
    main:                Main.hs
    source-dirs:         apps/egraphGP
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -fdistinct-constructor-tables
    - -finfo-table-map
    - -optc-O3
    - -eventlog
    dependencies:
    - srtree
    - optparse-applicative >= 0.17 && < 0.19
    - normaldistribution >= 1.1.0.3 && < 1.2 
  ieeexplore:
    main:                Main.hs
    source-dirs:         apps/ieeexplore
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O3
    dependencies:
    - srtree
    - optparse-applicative >= 0.17 && < 0.19

tests:
  srtree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - srtree
    - ad
    - HUnit

