name:                srtree
version:             2.0.1.8
synopsis:            A general library to work with Symbolic Regression expression trees.
github:              "folivetti/srtree"
license:             BSD3
author:              "Fabricio Olivetti de França"
maintainer:          "fabricio.olivetti@gmail.com"
category:            Math, Data, Data Structures
copyright:           "2023 Fabricio Olivetti de França"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A Symbolic Regression Tree data structure to work with mathematical expressions with support to first order derivative and simplification;

dependencies:
- base >= 4.19 && < 5
- mtl >= 2.2 && < 2.4
- containers >= 0.6.7 && < 0.9
- random >= 1.2 && < 1.4
- vector >= 0.12 && < 0.14
- filepath >= 1.4.0.0 && < 1.6
- split >= 0.2.5 && < 0.3
- zlib >= 0.6.3 && < 0.8
- bytestring >= 0.11 && < 0.13
- primitive
- deepseq
- async
- attoparsec >= 0.14.4 && < 0.15
- attoparsec-expr >= 0.1.1.2 && < 0.2
- parallel
- accelerate
- accelerate-llvm-native
- exceptions
- statistics 
- lens
- hashable
- binary
- unordered-containers
- ieee754

library:
  source-dirs: src
  extra-libraries:     nlopt
  ghc-options:
    - -fwarn-incomplete-patterns

executables:
  srtree-report:
    main:                Main.hs
    source-dirs:         apps/Report
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - srtree
    - optparse-applicative
    - accelerate
    - accelerate-llvm-native
    - attoparsec
    - bytestring
    - containers
    - deepseq
    - exceptions
    - filepath
    - mtl
    - parallel
    - primitive
    - random
    - split
    - statistics
    - vector
    - zlib

  bench:
    main:                Main.hs
    source-dirs:         apps/Bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -fllvm
    - -pgmlo opt-20
    - -pgmlc llc-20
    - -optlo-O3
    - -optlc-mcpu=native
    - -mavx2
    - -mfma
    - -fspec-constr
    - -fmax-simplifier-iterations=20
    - -fexpose-all-unfoldings
    dependencies:
    - srtree
    - criterion

  bench-eqsat:
    main:                Main.hs
    source-dirs:         apps/BenchEqSat
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - srtree
    - criterion

tests:
  srtree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - srtree
    - ad
    - HUnit
