name:                srtree
version:             2.0.0.0
synopsis:            A general library to work with Symbolic Regression expression trees.
github:              "folivetti/srtree"
license:             BSD3
author:              "Fabricio Olivetti de França"
maintainer:          "fabricio.olivetti@gmail.com"
category:            Math, Data, Data Structures
copyright:           "2023 Fabricio Olivetti de França"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A Symbolic Regression Tree data structure to work with mathematical expressions with support to first order derivative and simplification;

dependencies:
- base >= 4.16 && < 5
- mtl >= 2.2 && < 2.4
- containers >= 0.6 && < 0.7
- random >= 1.2 && < 1.3
- vector >= 0.12 && < 0.14
- dlist >= 1.0 && < 1.1
- massiv >= 1.0.4.0 && < 1.1
- filepath 
- split 
- zlib 
- bytestring >= 0.11 && < 0.12
- nlopt-haskell 
- statistics 
- attoparsec
- attoparsec-expr
- transformers
- deriving-compat
- text
- graphviz
- ieee
- lens 
- exceptions 

library:
  source-dirs: src
  ghc-options:
    - -fwarn-incomplete-patterns

executables:
  tinygp:
    main:                Main.hs
    source-dirs:         apps/tinygp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O3
    dependencies:
    - optparse-applicative >= 0.17 && < 0.19
    - srtree
  srtools:
    main:                Main.hs
    source-dirs:         apps/srtools
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O3
    dependencies:
    - srtree
    - bytestring >= 0.11 && < 0.12
    - optparse-applicative >= 0.17 && < 0.19
    - normaldistribution
  eqsatrepr:
    main:                Main.hs
    source-dirs:         apps/eqsatrepr
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O3
    dependencies:
    - srtree
  srsimplify:
    main:                Main.hs
    source-dirs:         apps/srsimplify
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O3
    dependencies:
    - optparse-applicative >= 0.17 && < 0.19
    - srtree
  egraphGP:
    main:                Main.hs
    source-dirs:         apps/egraphGP
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O3
    dependencies:
    - srtree
    - bytestring >= 0.11 && < 0.12
    - optparse-applicative >= 0.17 && < 0.19

tests:
  srtree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - srtree
    - ad
    - HUnit

